app.swagger:
    path: /api/doc.json
    controller: nelmio_api_doc.controller.swagger
    defaults: { _format: json }

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }


